### ISSUE TITLE
`AttributeError: 'NoneType' object has no attribute 'upper'` when edit-note used with ID

### ISSUE THREAD

**Issue by jdpopkin** [jbaiter/zotero-cli#11]
`zotcli edit-note BPMHDA6I` fails with this error:

```Traceback (most recent call last):
  File "/usr/local/bin/zotcli", line 9, in <module>
    load_entry_point('zotero-cli', 'console_scripts', 'zotcli')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jacksonpopkin/Developer/usr/src/oss/zotero-cli/zotero_cli/cli.py", line 260, in edit_note
    note = pick_note(ctx.obj, item_id, note_num)
  File "/Users/jacksonpopkin/Developer/usr/src/oss/zotero-cli/zotero_cli/cli.py", line 284, in pick_note
    notes = tuple(zot.notes(item_id))
  File "/Users/jacksonpopkin/Developer/usr/src/oss/zotero-cli/zotero_cli/backend.py", line 210, in notes
    notes = self._zot.children(item_id, itemType="note")
  File "/usr/local/lib/python2.7/site-packages/pyzotero/zotero.py", line 127, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/usr/local/lib/python2.7/site-packages/pyzotero/zotero.py", line 503, in children
    i=item.upper())
AttributeError: 'NoneType' object has no attribute 'upper'```

even though I really do have an item whose ID is `BPMHDA6I`.

I think I have a fix for this. I'll clean up all my hideous printlns and submit a PR.

**Comment by jbaiter** [comment]
This was fixed in https://github.com/jbaiter/zotero-cli/commit/5ad46e8388a109ab6afc8d31d28297e742e48528
