### ISSUE TITLE
no such table: items_idx

### ISSUE THREAD

**Issue by DancingQuanta** [jbaiter/zotero-cli#32]
Hi, on Cygwin with Anaconda Python 3.5 installed in Windows, I experienced an error when trying an query for the first time:

```$zotcli query "spin"
Traceback (most recent call last):
  File "C:\Users\andre\Anaconda3\Scripts\zotcli-script.py", line 11, in <module>
    load_entry_point('zotero-cli', 'console_scripts', 'zotcli')()
  File "C:\Users\andre\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\andre\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\andre\Anaconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\andre\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\andre\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\andre\Anaconda3\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\andre\repos\zotero-cli\zotero_cli\cli.py", line 184, in query
    for item in ctx.obj.search(query, limit):
  File "c:\users\andre\repos\zotero-cli\zotero_cli\index.py", line 132, in search
    for itm in cursor.execute(SEARCH_QUERY, (query, limit or -1)):
sqlite3.OperationalError: no such table: items_idx
```
I am using local storage with the storage path in config.ini.

I should add that because I am using Python on Windows, the sqlite is out of date (missing FTS4) and so I have to replace `sqlite3.dll` in `Anaconda/DLLs` with newer version in order to complete `zotero configure` successfully.

**Comment by jbaiter** [comment]
Could you try removing your database file and re-run `zotero configure`? It looks like something went wrong while initializing the database.

**Comment by DancingQuanta** [comment]
I have found that zoter-cli does not read config.ini for storage directory however I created a pull request #35  that searches zotero folder in Windows and Mac. So using this pull request `zotero-cli` can find the data file.
The error in OP still occurs though.

**Comment by DancingQuanta** [comment]
Okay, in Windows, the config.ini is actually stored in `~/AppData/Roaming/zotcli/`.
There is also `index.sqlite`  in that folder. Removing it resolves the issue of error relating to `items_idx`.
