### ISSUE TITLE
Mac python 2, able to query but not read or edit-note

### ISSUE THREAD

**Issue by kevintaylor** [jbaiter/zotero-cli#39]
New user. Mac Sierra. Python
$ python --version
Python 2.7.10

Am able to query my zotero db. E.G.

$ zotcli query Sullivan
[REFTHQBY] Sullivan and Miller: Segmenting the informal venture capital market: Economic, hedonistic, and altruistic investors (May 1996)

When reading or edit-noting, it chokes.

$ zotcli read sullivan
Traceback (most recent call last):
  File "/usr/local/bin/zotcli", line 9, in <module>
    load_entry_point('zotero-cli==0.3.0', 'console_scripts', 'zotcli')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/zotero_cli/cli.py", line 208, in read
    att_path = ctx.obj.get_attachment_path(read_att)
  File "/Library/Python/2.7/site-packages/zotero_cli/backend.py", line 239, in get_attachment_path
    "Attachment is not stored on server, cannot download!")
ValueError: Attachment is not stored on server, cannot download!

$ zotcli read REFTHQBY
Traceback (most recent call last):
  File "/usr/local/bin/zotcli", line 9, in <module>
    load_entry_point('zotero-cli==0.3.0', 'console_scripts', 'zotcli')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/zotero_cli/cli.py", line 198, in read
    attachments = ctx.obj.attachments(item_id)
  File "/Library/Python/2.7/site-packages/zotero_cli/backend.py", line 224, in attachments
    attachments = self._zot.children(item_id, itemType="attachment")
  File "/Library/Python/2.7/site-packages/pyzotero/zotero.py", line 129, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/Library/Python/2.7/site-packages/pyzotero/zotero.py", line 608, in children
    i=item.upper())
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by kevintaylor** [comment]
After using zotcli for a bit I realize this is caused by trying to add-note or edit-note to a library item that already has a note that was not created by zotcli.

My suggestion is to handle errors from this and let the user know they need to remove the non-zotcli note. Or, better, convert non-zotcli notes into markdown zotcli notes so they are editable.

**Comment by cbcoutinho** [comment]
I'm having the same issue as you, specifically with `zotcli` having trouble with the `'NoneType' object has no attribute 'upper'` error. I am unable to edit existing Zotero notes, which is understandable, but I'm also unable to edit notes I have created only using `zotcli` - that's pretty strange.

Further, notes I create using `zotcli` are placed in my 'Unfiled Items' catergory rather than under the item I originally intended.

NOTE: This was with python3 instead of python2

**Comment by lf-araujo** [comment]
Can confirm same error as @cbcoutinho  under archlinux, python3.

**Comment by pszenher** [comment]
Receiving the same error as @cbcoutinho and @lf-araujo under Ubuntu with python3
