### ISSUE TITLE
Getting the following error, any ideas?

### ISSUE THREAD

**Issue by Degiorgio** [jbaiter/zotero-cli#40]
Doing:
zotcli  add-note  "bla bla"

Getting the following error, any ideas? 

pyzotero.zotero_errors.HTTPError: 
Code: 500
URL: https://api.zotero.org/users/4509759/items/H2ZC2NX6
Method: PATCH
Response: An error occurred

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/k/anaconda3/bin/zotcli", line 11, in <module>
    sys.exit(cli())
  File "/home/k/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/k/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/k/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/k/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/k/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/k/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/k/anaconda3/lib/python3.6/site-packages/zotero_cli/cli.py", line 247, in add_note
    ctx.obj.create_note(item_id, note_body)
  File "/home/k/anaconda3/lib/python3.6/site-packages/zotero_cli/backend.py", line 321, in create_note
    fp.write(raw_data['text'].encode('utf-8'))
NameError: name 'raw_data' is not defined

**Comment by zhangbingxyx** [comment]
Same ,did you solved this problem?
