### ISSUE TITLE
Another edit-note error

### ISSUE THREAD

**Issue by okeshawarz** [jbaiter/zotero-cli#45]
A very similar error to #21. `query` and `add-note` work fine. When I go to `edit-note` on a note that was written on another machine and synced via the Zotero database, I get the following error:

```
$ zotcli edit-note engels
Traceback (most recent call last):
  File "/usr/lib/python3.7/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/encodings/base64_codec.py", line 19, in base64_decode
    return (base64.decodebytes(input), len(input))
  File "/usr/lib/python3.7/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.7/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jostar/.local/bin/zotcli", line 11, in <module>
    load_entry_point('zotero-cli==0.3.0', 'console_scripts', 'zotcli')()
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jostar/.local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jostar/.local/lib/python3.7/site-packages/zotero_cli/cli.py", line 260, in edit_note
    note = pick_note(ctx.obj, item_id, note_num)
  File "/home/jostar/.local/lib/python3.7/site-packages/zotero_cli/cli.py", line 284, in pick_note
    notes = tuple(zot.notes(item_id))
  File "/home/jostar/.local/lib/python3.7/site-packages/zotero_cli/backend.py", line 212, in notes
    note['data']['note'] = self._make_note(note)
  File "/home/jostar/.local/lib/python3.7/site-packages/zotero_cli/backend.py", line 277, in _make_note
    data = decode_blob(blobs[0])
  File "/home/jostar/.local/lib/python3.7/site-packages/zotero_cli/backend.py", line 81, in decode_blob
    blob_data = codecs.decode(blob_data, codec)
TypeError: decoding with 'base64' codec failed (TypeError: expected bytes-like object, not str)
```
If I try to edit via ID, I get the same error as in #21:

```
$ zotcli edit-note LYUD43NK
Traceback (most recent call last):
  File "/home/jostar/.local/bin/zotcli", line 11, in <module>
    load_entry_point('zotero-cli==0.3.0', 'console_scripts', 'zotcli')()
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jostar/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jostar/.local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jostar/.local/lib/python3.7/site-packages/zotero_cli/cli.py", line 260, in edit_note
    note = pick_note(ctx.obj, item_id, note_num)
  File "/home/jostar/.local/lib/python3.7/site-packages/zotero_cli/cli.py", line 284, in pick_note
    notes = tuple(zot.notes(item_id))
  File "/home/jostar/.local/lib/python3.7/site-packages/zotero_cli/backend.py", line 210, in notes
    notes = self._zot.children(item_id, itemType="note")
  File "/home/jostar/.local/lib/python3.7/site-packages/pyzotero/zotero.py", line 193, in wrapped_f
    retrieved = self._retrieve_data(func(self, *args))
  File "/home/jostar/.local/lib/python3.7/site-packages/pyzotero/zotero.py", line 761, in children
    u=self.library_id, t=self.library_type, i=item.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by p3palazzo** [comment]
The same error happens on Python 3.8.1.

**Comment by petRUShka** [comment]
Confirm recent zotcli from pip and Zotero 5.0.88

**Comment by mara-kr** [comment]
So, I found that the `DATA_PAT` in `backend.py` wasn't matching. I changed to:
```
DATA_PAT = re.compile(
    r'<div class="zotcli-note">.*<p .*title="(.+)">.*</div>',
    flags=re.DOTALL | re.MULTILINE)
```
Then, there's an issue with the regex match returning a string instead of a bytes object, so I added the following to the start of `decode_blob()`, since the regex matches a string like `"b'...'"`
```
    blob_data = eval(blob_data)
```

Yes, it's hacky. I'd love a nicer solution, but I wanted to get back to my research. With this, I can use the item ID if I use all lowercase characters, I don't think I'll bother chasing down why uppercase isn't working.

**Comment by ryan-heslin** [comment]
Thanks very much for the suggestion. Unfortunately, I can't get it working.
I created a test note and found the relevant entry in `itemNotes` in the `zotero.sqlite` database:

```
<div class="zotero-note znv1"><p>Test note</p>

    <div class="zotcli-note">
        <p xmlns="http://www.w3.org/1999/xhtml"
        id="zotcli-data" style="color: #cccccc;"
        xml:base="http://www.w3.org/1999/xhtml"
        title="b'eJyrVkrLL8pNLFGyUlDKSSxJrVDSUVACUmCBkNTiEoW8/JLUmDyQcFlqUXFmfh5QxsiwFgASOxII\n'">
        (hidden zotcli data)
        </p>
    </div></div>
``` 
 After modifying `backend.py`, the errors recur, exactly as you described, for both lower- and uppercase spelling of the item ID.
And I confirmed that your pattern successfully matched the title element of this example. Don't know what's going on.
